apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-example-mongodb
  namespace: kube-monitor
spec:
  endpoints:
  - path: /metrics
    port: 9216/TCP
    interval: 30s
  namespaceSelector:
    matchNames:
    - mongo
  selector:
    matchLabels:
      app: example-mongodb-metrics-svc